### ISSUE TITLE
oauth errors out when a querystring is provided

### ISSUE THREAD

**Issue by bebraw** [netdna/node-netdna#5]
Hi,

Just noticed a slight issue at that [custom version of of node-oauth](https://github.com/niftylettuce/node-oauth) you are using. It is missing `querystring` require (renamed as `qs` apparently). This seems to have been fixed [in the original version](https://github.com/ciaranj/node-oauth).

You can trigger this issue by invoking something like `netdna.get('reports/stats.json?date_from=2013-06-07', function() {...})`. Basically I was trying to fetch data based on a specific range when I ran upon this issue.

**Comment by jmervine** [comment]
See https://github.com/maxcdn/node-maxcdn
